🚨 Code has an error.
📋 Details:
XHRGET
http://localhost:8000/networks/test_network/graph
[HTTP/1.1 404 Not Found 94ms]

XHRGET
http://localhost:8000/networks/test_network/graph
[HTTP/1.1 404 Not Found 96ms]

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8000/networks/test_network/graph. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 404.

TypeError: NetworkError when attempting to fetch resource. <anonymous code>:1:147461
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8000/networks/test_network/graph. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 404.

TypeError: NetworkError when attempting to fetch resource.